name: App CD Pipeline

on:
  workflow_run:
    workflows: ["App CI Pipeline"]
    types:
      - completed
    branches: [ main ]

env:
  PYTHON_VERSION: '3.10'

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        chmod 600 .env

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt gunicorn

    - name: Database migrations
      run: |
        python app/manage.py migrate --noinput

    - name: Collect static files
      run: |
        python app/manage.py collectstatic --noinput

    - name: Restart services
      run: |
        sudo systemctl daemon-reload
        sudo systemctl restart gunicorn
        sudo systemctl restart celery
        sudo systemctl restart celery-beat
